"""added name for playlist

Revision ID: 55c488ce12eb
Revises: a01892b2624e
Create Date: 2021-02-09 17:47:41.563166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c488ce12eb'
down_revision = 'a01892b2624e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'name')
    # ### end Alembic commands ###
